package com.boxin.base.model;

import java.util.Date;

/**
 * Created by zy on 2015/4/17.
 */
public class ManageUserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bx_manage_user_role.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bx_manage_user_role.role_id
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bx_manage_user_role.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    private String UserName;

    private String code;

    private String roleName;

    public String getUserName() {
        return UserName;
    }

    public void setUserName(String userName) {
        UserName = userName;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bx_manage_user_role.user_id
     *
     * @return the value of bx_manage_user_role.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bx_manage_user_role.user_id
     *
     * @param userId the value for bx_manage_user_role.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bx_manage_user_role.role_id
     *
     * @return the value of bx_manage_user_role.role_id
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bx_manage_user_role.role_id
     *
     * @param roleId the value for bx_manage_user_role.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bx_manage_user_role.create_time
     *
     * @return the value of bx_manage_user_role.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bx_manage_user_role.create_time
     *
     * @param createTime the value for bx_manage_user_role.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}
