package com.boxin.base.daogen;

import com.boxin.base.model.ManagePermission;

public interface ManagePermissionMapperGen {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_manage_permission
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_manage_permission
     *
     * @mbggenerated
     */
    int insert(ManagePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_manage_permission
     *
     * @mbggenerated
     */
    int insertSelective(ManagePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_manage_permission
     *
     * @mbggenerated
     */
    ManagePermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_manage_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ManagePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_manage_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ManagePermission record);
}