package com.boxin.base.daogen;

import com.boxin.base.model.ManageRole;

public interface ManageRoleMapperGen {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_manage_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_manage_role
     *
     * @mbggenerated
     */
    int insert(ManageRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_manage_role
     *
     * @mbggenerated
     */
    int insertSelective(ManageRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_manage_role
     *
     * @mbggenerated
     */
    ManageRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_manage_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ManageRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_manage_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ManageRole record);
}