package com.boxin.base.daogen;

import com.boxin.base.model.ManageRolePermission;

public interface ManageRolePermissionMapperGen {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_manage_role_permission
     *
     * @mbggenerated
     */
    int insert(ManageRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_manage_role_permission
     *
     * @mbggenerated
     */
    int insertSelective(ManageRolePermission record);
}